{{- $root := . -}}
{{- range append .Values.watchNamespaces .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if $root.Values.watchAnyNamespace }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
metadata:
  {{- if $root.Values.watchAnyNamespace }}
  name: strimzi-cluster-operator-east-2-namespaced
  {{- else }}
  name: strimzi-cluster-operator-east-2
  {{- end }}
  namespace: {{ . }}
  labels:
    app: {{ template "strimzi.name" $root }}
    chart: {{ template "strimzi.chart" $root }}
    component: role-binding
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
subjects:
  - kind: ServiceAccount
    name: strimzi-cluster-operator-east-2
    namespace: {{ $root.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: strimzi-cluster-operator-east-2-namespaced
  apiGroup: rbac.authorization.k8s.io
{{- end }}
